language: c

branches:
  only:
  - master

sudo: false

before_install:
- sudo add-apt-repository ppa:snaipewastaken/ppa -y
- sudo apt-get update -q
- sudo apt-get install criterion-dev -y


install:
- "cmake . -DENABLE_TESTS=ON"
- make

script:
- ctest

after_failure:
- cat Testing/Temporary/LastTest.log

